logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Warszawa5584
    url: jdbc:mysql://localhost:3306/SpringbootAngularToDockerDb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true